service: moverwebapp-production
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "10m"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 25
  min_pending_latency: 50ms
  max_pending_latency: automatic
  max_concurrent_requests: 50


handlers:

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /css/(.*)
  static_files: www/css/\1
  upload: www/css/(.*)
  secure: always

- url: /fonts/(.*)
  static_files: www/fonts/\1
  upload: www/fonts/(.*)
  secure: always

- url: /js/(.*)
  static_files: www/js/\1
  upload: www/js/(.*)
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://app.viamover.com

- url: /img/(.*)
  static_files: www/img/\1
  upload: www/img/(.*)
  secure: always

- url: /media/(.*)
  static_files: www/media/\1
  upload: www/media/(.*)
  secure: always

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico
  secure: always

- url: /intercom-web-init.js
  static_files: www/intercom-web-init.js
  upload: www/intercom-web-init.js
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://app.viamover.com

- url: /remove-all
  static_files: www/remove-index.html
  upload: www/remove-index.html
  secure: always
  expiration: "1m"

- url: /(.*)
  static_files: www/index.html
  upload: www/index.html
  secure: always
  expiration: "0d 0h"
