export const APIKeys = {
  ZERION_API_KEY: 'Demo.ukEVQp6L5vfgxcz4sBke7XvS873GMYHy',
  ZERION_API_KEY_ORIGIN: 'http://localhost:3000',
  ETHERSCAN_API_KEY: '5EUNNI2I5KDVVDAE81AYTXHEHCJUI3RKDU',
  GAS_STATION_API_KEY: ''
};
