export const voteHubBaseUrl = 'https://vote.holyheld.com';
export const scoresApiBaseUrl = 'https://vote.holyheld.com/api';
export const graphqlUrl = voteHubBaseUrl + '/graphql';
export const defaultClientVersion = '0.1.3';
export const moverSpaceId = 'mover';
export const defaultCachePeriodSeconds = 60;
export const minimumVotingThresholdMultiplier = 0.4;
export const defaultProposalDurationDays = 3;
export const defaultPowerNeededToBecomeAProposer = 10000;
