export { default as GovernanceOverview } from './governance-overview.vue';
export { default as GovernanceProposal } from './governance-proposal.vue';
export { default as GovernanceProposalCreateOverview } from './governance-proposal-create-overview.vue';
export { default as GovernanceProposalDetails } from './governance-proposal-details.vue';
export { default as GovernanceProposalOverview } from './governance-proposal-overview.vue';
export { default as GovernanceProposals } from './governance-proposals.vue';
export { default as GovernanceStats } from './governance-stats.vue';
export { default as GovernanceNavMyGovernance } from './governance-nav-my-governance.vue';
export { default as GovernanceNavManageGovernance } from './governance-nav-manage-governance.vue';
